/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Model(props) {
  const { nodes, materials } = useGLTF("/model/plane.glb");
  return (
    <group {...props} dispose={null}>
      <group
        position={[-0.002, 0.518, -1.724]}
        rotation={[Math.PI / 2, 0, -1.572]}
        scale={[0.359, 0.079, 0.24]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane021.geometry}
          material={materials["Material.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane021_1.geometry}
          material={materials["Material.001"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/model/plane.glb");
